# Generated by Django 4.2.6 on 2023-11-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.IntegerField(choices=[(1, 'Food'), (2, 'Health'), (3, 'Sports'), (4, 'Technology')]),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
