# Generated by Django 4.2.6 on 2023-11-01 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_blog.category')),
            ],
        ),
    ]
