# Generated by Django 4.2.6 on 2023-11-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_post_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
