# Generated by Django 4.2.6 on 2023-11-08 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0013_alter_save_pid_alter_save_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='cat',
            field=models.ForeignKey(choices=[(1, 'Food'), (2, 'Health'), (3, 'Sports'), (4, 'Technology')], on_delete=django.db.models.deletion.CASCADE, to='my_blog.category'),
        ),
    ]
